on:
  pull_request:
    branches:
      - Development
  pull_request:
    branches:
      - master

name: Website Testing

jobs:
  HTMLProofer:
    name: HTMLProofer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: HTMLProofer
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./public_html"
          arguments: --disable-external
